import java.util.Hashtable;
import javax.imageio.ImageIO;
import java.util.Scanner;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.PrintStream;
import java.lang.Object;
import java.lang.*;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.lang.reflect.Field;
import java.lang.reflect.ParameterizedType;
import java.util.ArrayList;
import java.util.List;
import java.lang.Math;
import java.text.DecimalFormat;
import java.io.FileNotFoundException;
import java.lang.Double;
import java.io.FileOutputStream;
import java.lang.String;
public class DeclareHash {
	public static int Declare(Hashtable<String , Integer> Loops) {
		Loops.put("A",1);
		Loops.put("B",2);
		Loops.put("C",0);
		Loops.put("D",1);
		Loops.put("E",0);
		Loops.put("F",0);
		Loops.put("G",0);
		Loops.put("H",0);
		Loops.put("I",0);
		Loops.put("J",0);
		Loops.put("K",0);
		Loops.put("L",0);
		Loops.put("M",0);
		Loops.put("N",0);
		Loops.put("O",1);
		Loops.put("P",1);
		Loops.put("Q",1);
		Loops.put("R",1);
		Loops.put("S",0);
		Loops.put("T",0);
		Loops.put("U",0);
		Loops.put("V",0);
		Loops.put("W",0);
		Loops.put("X",0);
		Loops.put("Y",0);
		Loops.put("Z",0);
		Loops.put("a",1);
		Loops.put("b",1);
		Loops.put("c",0);
		Loops.put("d",1);
		Loops.put("e",1);
		Loops.put("f",0);
		Loops.put("g",-1);
		Loops.put("h",0);
		Loops.put("i",0);
		Loops.put("j",0);
		Loops.put("k",0);
		Loops.put("l",0);
		Loops.put("m",0);
		Loops.put("n",0);
		Loops.put("o",1);
		Loops.put("p",1);
		Loops.put("q",1);
		Loops.put("r",0);
		Loops.put("s",0);
		Loops.put("t",0);
		Loops.put("u",0);
		Loops.put("v",0);
		Loops.put("w",0);
		Loops.put("y",0);
		Loops.put("x",0);
		Loops.put("z",0);
		Loops.put("1",0);
		Loops.put("2",1);
		Loops.put("3",1);
		Loops.put("4",1);
		Loops.put("5",0);
		Loops.put("6",1);
		Loops.put("7",0);
		Loops.put("8",2);
		Loops.put("9",0);
		return 0;
	}
}
